ACCOUNTS = [ "GCQBVSARJXE4MCDOD7CZ2BNIB34KQ7KM4VO3OCHJXCJQW3IOYWOGWDLP" ]
VERSION = "0.1.0"
SIGNING_KEY = "GCQBVSARJXE4MCDOD7CZ2BNIB34KQ7KM4VO3OCHJXCJQW3IOYWOGWDLP"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

WEB_AUTH_ENDPOINT = "https://stellar.beign.es/auth"

[[PRINCIPALS]]
name = "Felix Perron-Brault"
email = "fpbrault@beign.es"
keybase = "fpbrault"
github = "https://www.github.com/fpbrault"

[DOCUMENTATION]
ORG_NAME = "fpbcraft"
ORG_URL = "https://stellar.beign.es"
ORG_DESCRIPTION = "SEP-0010 reference server."